#!/usr/bin/bash
BD=$(dirname $0)/
case $1 in 
  check)
    for kf in $(find -name KankuFile);do
      P=`dirname $kf`
      F=`basename $kf`
      T=$(echo $P|perl -p -e "s#$BD##"|perl -p -e 's#/#.#g')
      cd $P
      gpg --verify $F.asc >> /dev/null 2>&1 \
	&& echo "ok - $T" \
	|| echo "not ok - $T"
      cd -
    done
  ;;
  sign)
    for kf in $(find -name KankuFile);do
      P=`dirname $kf`
      F=`basename $kf`
      cd $P
      gpg --verify $F.asc >> /dev/null 2>&1 \
	&& echo "ok - $P" \
	|| {
	  echo "not ok - $P";
          rm -f $F.asc
	  gpg -b -a $F
        }
      cd -
    done
  ;;
  *)
    echo "Usage: "`basename $0`" <check|sign>"
    exit 1
  ;;
esac
